version: "3"
services:
  reactapp:
    container_name: absen
    working_dir: /var/app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - .:/var/app:Z
    command: bash /var/app/init.sh
    ports:
      - "80:3000"